sudo: required
services:
  - docker
language: go
go:
  - '1.7'
env:
  global:
    - REPO=quay.io/koudaiii/newrelic-gin-sample
    - BRANCH=$(echo $TRAVIS_BRANCH | sed -e "s,/,_,g;")
    - TAG=$BRANCH-${TRAVIS_COMMIT::8}
install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -q
  - sudo apt-get install glide -y
  - mkdir -p $GOPATH/bin
script:
  - script/ci-build
deploy:
  skip_cleanup: true
  provider: script
  script: ./script/ci-deploy
  on:
    all_branches: true

