---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: newrelic-gin-sample
  namespace: newrelic-gin-sample
  labels:
    name: newrelic-gin-sample
    role: web
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      name: newrelic-gin-sample
      labels:
        name: newrelic-gin-sample
        role: web
    spec:
      imagePullSecrets:
      - name: wantedlybotkey
      containers:
      - image: quay.io/koudaiii/newrelic-gin-sample:latest
        name: newrelic-gin-sample
        ports:
        - containerPort: 8080 # Deployment containerPort (Opened Port)
        env:
        - name: NEWRELIC_LICENSE_KEY # e.g. RACK_ENV
          valueFrom:
            secretKeyRef:
              name: dotenv
              key: app-newrelic-license-key
